### ISSUE TITLE
LuaDoc测试跑不过；生成的ast中不包含doc信息

### ISSUE THREAD

**Issue by ArtistArthur** [sumneko/LuaParser#5]
我在本地跑`main.lua`，打断点发现好像生产的ast中不会生成doc相关的内容，我也看到了您把``test 'LuaDoc'``给注释掉了，这个parser目前不支持doc吗？  
我想要看下doc是怎样被放在变量里的，怎么才能正确解析doc呢？

**Comment by sumneko** [comment]
解析代码在 `luadoc.lua` 里。没跑测试的原因很简单，我懒得写测试了。

流程是先用 `compile.lua` 解析出基础语法树，其中包含了注释信息。然后把这个语法树扔到 `luadoc.lua` 里面跑，会把注释生成出 LuaDoc 并绑定到附近的 source 上。

**Comment by ArtistArthur** [comment]
好的，感谢
