### ISSUE TITLE
compile：getname时，只能获取到定义时的信息，而不能获取到赋值改变时的信息

### ISSUE THREAD

**Issue by ArtistArthur** [sumneko/LuaParser#6]
例如以下情况：
![image](https://user-images.githubusercontent.com/40695061/131099501-1de5bfd4-3aad-4bc7-8f4a-21a21c1f99bf.png)
我看相应compile代码中，编译getname的结点时，是直接去最近的block中的`locals`中寻找符号，因此只能拿到定义local的时候的信息，如果中间有`setlocal`等动作，那么不能拿到真正的对象信息
![image](https://user-images.githubusercontent.com/40695061/131099821-4369d014-022c-4485-bf35-8014f47cc4a2.png)
比如这个地方有一个赋值语句`id2 = id1`那么实际上`id2`的对象信息应该绑定到`id1`上，但是这个动作没有放在`locals`表里，因此当编译`local name = id2`这句话时，寻找`id2`的过程中错过了`id2 = id1`这一动作，导致`name`被绑定到`local id2 = 2`，这个地方是不是有改进的余地？  
我觉得`locals`里面是不是不应该放一个语法结构的结点，而是应该放变量代表的结点，这样的话，当变量的value变了，其他引用这个结点的对象也可以跟着变。 
或者在`guide.getLocal`的时候，不仅仅寻找`locals`里的东西，还要寻找其他语句中的`setlocal`

**Comment by sumneko** [comment]
我想实现的类型检查类似于TS的策略，即赋值的时候不会收窄类型。同时只检查显性标记类型的对象，例如在TS中：

```ts
let x;
x = 1;
x; // 这里依然是 any
```

对应到lua就是：

```lua
local x
x = 1
print(x)
```

在这个例子中，我会将 `x` 推断为数字，但这是根据使用情况来进行的弱推断，不应该作为类型检查的依据。
我的想法是，只根据强定义来进行类型检查，即通过注解或是在local时的赋值。

真正需要考虑的类型收窄是这2种情况，TS中：

```ts
let x: number|boolean;

if (typeof x == 'number') {
    x; // 这里是 number
} else {
    x; // 这里是 boolean
}
x as boolean; // 这里是 boolean
```

考虑到lua的注解语法，对应的lua可以是：

```lua
---@type number|boolean
local x

if type(x) == 'number' then
    print(x) -- 这里的x应该是number
else
    print(x) -- 这里的x应该是boolean
end
---@narrow x boolean
print(x) -- 这里的x是 boolean
```

if 分支里的自动识别可以先不做，要求用户手动用注解标记。
之后的问题就是如何实现narrow。

**Comment by ArtistArthur** [comment]
哦哦，这样我觉得您的想法更合理以及更好。  
另外我有个疑惑，您为什么记录符号或者结构的字符数位置，而不按照行号+列号的方式记录位置呢？（是我的使用方式不对吗？我用您这种方式不好找目标位置）

**Comment by sumneko** [comment]
我是用lpeg解析的，默认就是返回的字符偏移位置，转换行号+列号会有额外开销，我就没转。
不过我目前正在改成行列的方式记录位置，见 https://github.com/sumneko/LuaParser/tree/newparser

**Comment by ArtistArthur** [comment]
哦哦。  
可能是我不会lpeg的原因，我觉得看grammar的代码好难且好烦。我看到有其他一些用常见的手写递归下降的方式（或者是翻译的官方的C代码来的），这种我看得懂所以觉得挺舒服的。  
我刚刚去看了下您的newparser，您准备不用lpeg了？（真是太棒了）  
如果是不用lpeg了，理由是什么呢？仅仅是因为行号的问题吗？

**Comment by sumneko** [comment]
直接原因是行号不好处理。此外之前解析完后我要对语法树再处理3次，我试试能不能合并到解析里一次做完。

**Comment by ArtistArthur** [comment]
我目前看到的是compile一次，luadoc算一次吗？请问是哪三次呢？  
另外目前您是怎么解决行号的问题的呀？我在LuaParser里面好像没有看到处理的地方。

**Comment by sumneko** [comment]
1. grammar + ast
2. compile
3. LuaDoc
4. noder

**Comment by ArtistArthur** [comment]
哦哦。另外我看到offset转换为行号+列号的地方了，是在guide里面。那目前看来好像也没有很麻烦，每次都去再找一次，用二分找开销也还可以？

**Comment by ArtistArthur** [comment]
您好，我看了部分您的noder相关的代码，但是很多地方不太懂：  
noder这个文件的作用是什么呢？它是用来解决什么问题的？
forward和backward相关的作用是什么呢？  
十分感谢您一直以来的耐心解答

**Comment by sumneko** [comment]
> 您好，我看了部分您的noder相关的代码，但是很多地方不太懂：
> noder这个文件的作用是什么呢？它是用来解决什么问题的？
> forward和backward相关的作用是什么呢？
> 十分感谢您一直以来的耐心解答

简单的说就是建立索引，比如 `x = y` 建立 a 到 b 的forward与 b 到 a 的backward，之后 searcher 的时候就不需要处理具体的语义，只需要根据缓存好的索引进行抽象搜索
